# Generated by Django 3.1.3 on 2020-11-16 15:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('added_on', models.DateField(blank=True, default=datetime.date.today)),
                ('genre', models.CharField(choices=[('FPS', 'First person shot'), ('PUZ', 'Puzzle'), ('STR', 'Strategy')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ComputerGame',
                'verbose_name_plural': 'ComputerGame',
                'ordering': ['name'],
            },
        ),
    ]
