# Generated by Django 3.1.2 on 2021-01-24 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComputerGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computergame',
            name='added_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 1, 24, 23, 48, 18, 570568)),
        ),
    ]
